### ISSUE TITLE
Documentation on using withing scos-sensor

### ISSUE THREAD

**Issue by dirkcgrunwald** [NTIA/scos-usrp#26]
I'm trying to set up a demo scos-sensor using a USRP 

In README.md there are references to setting
```
BASE_IMAGE=smsntia/uhd_b2xx_py3
```
and also
```
ghcr.io/ntia/scos-usrp/scos_usrp_uhd
```

The smsntia account doesn't appear to be on docker hub anymore. It's not clear from the documentation if you're expected to build and push your own scos-usrp image or if e.g. the hosted on ghcr.io is usable by anyone.

Whatever the intent is, it would be useful to update the documentation to make it easier for people trying this out.

**Comment by jhazentia** [comment]
Thank you for posting this issue. The `ghcr.io` link is the correct one. It is a docker image publicly available in the GitHub container registry. The README has been updated with the correct URL in the latest release. Let us know if you have any additional questions.
