### ISSUE TITLE
scos-usrp lags upstream changes to SignalAnalyzerInterface

### ISSUE THREAD

**Issue by aromanielloNTIA** [NTIA/scos-usrp#27]
This repo has not kept up with development in SCOS Sensor and SCOS Actions. We need a general update to address changes that have been made to the SignalAnalyzerInterface, and need to test a generic USRP sensor running those changes. The scos-tekrsa implementation is current and can be used as a reference where needed.

**Comment by jhazentia** [comment]
Fixed in #28
